# Generated by Django 6.0.1 on 2026-02-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_alter_exerciseplan_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_session_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_session_report",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
