# Generated by Django 6.0.1 on 2026-02-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_userprofile_last_session_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="session_saved_today",
            field=models.BooleanField(default=False),
        ),
    ]
