# Generated by Django 6.0.1 on 2026-02-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0009_alter_userprofile_last_activity"),
        ("tracker", "0009_dailyprogress"),
    ]

    operations = []
