# Generated by Django 6.0.1 on 2026-01-30 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="last_active_date",
            new_name="last_activity",
        ),
    ]
